name: iOS App Signing

on:
  repository_dispatch:
    types: [sign-app]

jobs:
  sign:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download required files
      - name: Download Files
        run: |
          curl -o app.ipa "${{ github.event.client_payload.ipa_url }}"
          curl -o certificate.p12 "${{ github.event.client_payload.p12_url }}"
          curl -o profile.mobileprovision "${{ github.event.client_payload.mobileprovision_url }}"

      # Step 3: Import Certificate
      - name: Import Certificate
        run: |
          security import certificate.p12 -k ~/Library/Keychains/login.keychain -P "${{ github.event.client_payload.p12_password }}"

      # Step 4: Re-sign IPA File
      - name: Re-sign IPA
        run: |
          mkdir resigned
          /usr/bin/codesign --force --sign "Apple Distribution: Your Name" --entitlements profile.mobileprovision app.ipa
          mv app.ipa resigned/signed_app.ipa

      # Step 5: Upload Signed IPA
      - name: Upload Signed IPA
        uses: actions/upload-artifact@v3
        with:
          name: signed-app
          path: resigned/signed_app.ipa
